## -----------------------------------------------
## Basic Configuration
## -----------------------------------------------

title = "Welcome to #WAIQ Age"
copyright = "{year}"

## -----------------------------------------------
## Publish
## -----------------------------------------------

relativeURLs = "true"
#canonifyURLs = "true"

# Local
#baseURL = "/"
publishDir = "public"

# Remote
baseURL = "https://waiq-full.netlify.app/"
#publishDir = "//centos/sites/hugodev/hugostory/"

## -----------------------------------------------
## Hugo Built-in Features
## -----------------------------------------------

#disableKinds = ["taxonomy", "section"]

## -----------------------------------------------
## Analytics support
## -----------------------------------------------

#googleAnalytics: G-MEASUREMENT_ID
swetrixAnalytics = "3UYKaHJP56by"

## -----------------------------------------------
## Site Parameters
## -----------------------------------------------

[Params]
  description = "A (modular, highly tweakable) responsive one-page theme for Hugo"
  logo = "images/banner.jpg"
  favicon = true
  gated = true

[Params.social]

[Params.asset]

## -----------------------------------------------
## Site Parameters
## -----------------------------------------------

[build]
  publish = "public"
  command = "hugo --gc --minify"

[build.environment]
  HUGO_VERSION = "0.134.2"
  HUGO_ENV = "production"
